"""empty message

Revision ID: 48714cf4e67b
Revises: 
Create Date: 2017-09-30 10:17:10.302148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48714cf4e67b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    op.add_column('tag', sa.Column('fun', sa.String(length=50), nullable=True))
    op.alter_column('tag', 'is_collection',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'is_collection',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('tag', 'fun')
    op.create_table('content',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('blocks_data', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('links_data', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
