"""empty message

Revision ID: 4e10fd894fed
Revises: 48714cf4e67b
Create Date: 2017-09-30 10:21:24.893779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e10fd894fed'
down_revision = '48714cf4e67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'fun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('fun', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
